{{ if and (ne .Values.environment "ci") (.Values.grafana.enabled) }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: w3f
  namespace: default
spec:
  secretName: w3f-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - grafana.{{ .Values.domain }}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - grafana.{{ .Values.domain }}
{{ end }}
