apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: w3f-common
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  tls:
  - hosts:
      - grafana.{{ .Values.domain }}
    secretName: w3f-tls
  rules:
  - host: grafana.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
