{{ if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@web3.foundation

    privateKeySecretRef:
      name: letsencrypt

    solvers:
    - dns01:
        cloudflare:
          email: cloudflare@web3.foundation
          apiKeySecretRef:
            name: cloudflare-credentials
            key: api-key
{{ end }}
