{{ if .Values.cloudflareApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
data:
  api-token: {{ .Values.cloudflareApiToken | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
data:
  api-token: {{ .Values.cloudflareApiToken | b64enc }}

{{ end }}
