{{- define "arkCredentials" }}
{{- printf "[default]\naws_access_key_id=%s\naws_secret_access_key=%s" .Values.spacesAccessToken .Values.spacesSecretKey | b64enc }}
{{- end }}
{{ if .Values.ark.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: arkcred
  namespace: heptio-ark
type: Opaque
data:
  cloud: {{ template "arkCredentials" . }}
  digitalocean_token: {{ .Values.digitalOceanToken | b64enc }}
{{ end }}
