environments:
  production:
  ci:

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager  # https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm
  version: v0.13.0  # Update has dependency in scripts/preflight.sh
