environments:
  production:
  ci:

repositories:
- name: loki
  url: https://grafana.github.io/loki/charts

releases:
- name: grafana
  chart: stable/grafana
  version: 2.3.5
  values:
  - ./config/grafana-values.yaml.gotmpl
- name: loki
  chart: loki/loki-stack
  version: 0.11.0
