{{ if and (ne .Values.environment "ci") ( .Values.alertRules.create ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: w3f
  name: general
spec:
  groups:
  - name: general.rules
    rules:
    - alert: TargetDownShort
      annotations:
        message: '{{`{{ $value }}`}}% of the {{`{{ $labels.job }}`}} targets are down.'
      expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
      for: 10m
      labels:
        severity: warning
    - alert: TargetDownLong
      annotations:
        message: '{{`{{ $value }}`}}% of the {{`{{ $labels.job }}`}} targets are down.'
      expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
      for: 30m
      labels:
        severity: critical
{{ end }}
