{{ if and (ne .Values.environment "ci") ( .Values.alertRules.create ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: w3f
  name: prometheus-operator
spec:
  groups:
  - name: prometheus-operator
    rules:
    - alert: PrometheusOperatorAlertmanagerReconcileErrors
      annotations:
        message: Errors while reconciling Alertmanager in {{`{{ $labels.namespace }}`}} Namespace.
      expr: |
        rate(prometheus_operator_reconcile_errors_total{job="prometheus-operator-operator",controller="alertmanager"}[5m]) > 0.1
      for: 10m
      labels:
        severity: warning
    - alert: PrometheusOperatorPrometheusReconcileErrors
      annotations:
        message: Errors while reconciling Prometheus in {{`{{ $labels.namespace }}`}} Namespace.
      expr: |
        rate(prometheus_operator_reconcile_errors_total{job="prometheus-operator-operator",controller="prometheus"}[5m]) > 0.1
      for: 10m
      labels:
        severity: warning
    - alert: PrometheusOperatorNodeLookupErrors
      annotations:
        message: Errors while reconciling Prometheus in {{`{{ $labels.namespace }}`}} Namespace.
      expr: |
        rate(prometheus_operator_node_address_lookup_errors_total{job="prometheus-operator-operator",controller="prometheus"}[5m]) > 0.1
      for: 10m
      labels:
        severity: warning
{{ end }}
